#!/usr/bin/env bash

# Display username, user ID, and home directory of each user from /etc/passwd

exec 3</etc/passwd

while IFS=':' read -r username uid _ _ home _; do
    echo "$username:$uid:$home"
done <&3

exec 3<&-
