#!/usr/bin/env bash
# Display information about each user from /etc/passwd using a while loop + IFS
# Open /etc/passwd file for reading
exec 3< /etc/passwd

# Read each line of /etc/passwd
while IFS=':' read -r username password uid gid info home shell; do
    # Extract additional information from /etc/passwd
    gang=$(getent group "$gid" | cut -d ':' -f1)
    passcode=$(echo "$password" | cut -d '$' -f3)
    
    # Display information about the user
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $info"
done <&3

# Close the file descriptor
exec 3<&-
