#!/usr/bin/env bash
# This script displays a list of currently running processes, including those without a TTY, in a user-oriented format and shows the process hierarchy.

ps -eo user,lstart,cmd --forest | awk '{print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12}'
