#!/usr/bin/env bash
# This script stops the 7-highlander process

# Check if the 7-highlander process is running
if pgrep -f "7-highlander" >/dev/null; then
  echo "7-highlander is already running"
else
  # Start the 7-highlander process
  ./7-highlander &
  echo "OK"

fi
